version: 2.1

orbs:
  ruby: circleci/ruby@2.5.2


executors:
  android-docker:
    docker:
      - image: cimg/android:2025.02.1
  ruby-docker:
    docker:
      - image: cimg/ruby:3.4.2

commands:
  ruby-install:
    description: Install Ruby
    steps:
      - ruby/install:
          version: 3.4.2
  ruby-show:
    description: Show installed Ruby
    steps:
      - run:
          command: which ruby
      - run:
          command: ruby --version

jobs:
  ruby-with-install:
    executor: ruby-docker
    steps:
      - ruby-install
      - ruby-show
  ruby-without-install:
    executor: ruby-docker
    steps:
      - ruby-show
  android-with-install:
    executor: android-docker
    steps:
      - ruby-install
      - ruby-show
  android-without-install:
    executor: android-docker
    steps:
      - ruby-show

workflows:
  main:
    jobs:
      - ruby-with-install
      - ruby-without-install
      - android-with-install
      - android-without-install
